version: '3.9'

services:
  django:
    image: django-docker:0.0.1
    container_name: django_container
    build: .
    ports:
      - "8000:8000"
    command: python3 manage.py runserver
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
  web: 
    build: .
    command: python3 manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db